COPDGene_P1_PROTEINS = "output/copdgene_soma_protname.txt"
COPDGene_P1_SNPS = "output/copdgene_recoded_str_p1.csv"
COPDGene_P1_NAME = "COPDGene_P1"
COPDGene_P1_CLINICAL = "/Users/andrew/Documents/Work/Datasets/clinical/COPDGene_P1P2P3_Flat_SM_NS_Mar20.txt"
COPDGene_P1_RACE_COL = "race"
COPDGene_P1_GENDER_COL = "gender"
COPDGene_P1_SID_COL = "sid"
COPDGene_P1_AGE_COL = "Age_P1"

COPDGene_P2_PROTEINS = "output/copdgene_p2_soma_protname.txt"
COPDGene_P2_SNPS = "output/copdgene_recoded_str_p1.csv"
COPDGene_P2_NAME = "COPDGene_P2"
COPDGene_P2_CLINICAL = "/Users/andrew/Documents/Work/Datasets/clinical/COPDGene_P1P2P3_Flat_SM_NS_Mar20.txt"
COPDGene_P2_RACE_COL = "race"
COPDGene_P2_GENDER_COL = "gender"
COPDGene_P2_SID_COL = "sid"
COPDGene_P2_AGE_COL = "Age_P2"

COPDGene_P2_5K_PROTEINS = "output/5k/copdgene_p2_5k_soma_protname.txt"
COPDGene_P2_5K_SNPS = "output/5k/copdgene_recoded_str_p2_5k.csv"
COPDGene_P2_5K_NAME = "COPDGene_P2_5K"
COPDGene_P2_5K_CLINICAL = "/Users/andrew/Documents/Work/Datasets/clinical/COPDGene_P1P2P3_Flat_SM_NS_Mar20.txt"
COPDGene_P2_5K_RACE_COL = "race"
COPDGene_P2_5K_GENDER_COL = "gender"
COPDGene_P2_5K_SID_COL = "sid"
COPDGene_P2_5K_AGE_COL = "Age_P2"

COPDGene_P2_5K_ALL_PROTEINS = "output/5k_all/copdgene_p2_5k_1727_soma_protname.txt"
COPDGene_P2_5K_ALL_SNPS = "output/5k_all/copdgene_recoded_str_p2_5k_1727.csv"
COPDGene_P2_5K_ALL_NAME = "COPDGene_P2_5K_ALL"
COPDGene_P2_5K_ALL_CLINICAL = "/Users/andrew/Documents/Work/Datasets/clinical/COPDGene_P1P2P3_Flat_SM_NS_Mar20.txt"
COPDGene_P2_5K_ALL_RACE_COL = "race"
COPDGene_P2_5K_ALL_GENDER_COL = "gender"
COPDGene_P2_5K_ALL_SID_COL = "sid"
COPDGene_P2_5K_ALL_AGE_COL = "Age_P2"

SPIROMICS_PROTEINS = "output/spiromics_soma_protname.txt"
SPIROMICS_SNPS = "output/spiromics_recoded_str_p1.csv"
SPIROMICS_NAME = "SPIROMICS"
SPIROMICS_CLINICAL = "/Users/andrew/Documents/Work/Datasets/clinical/CORE6_3_clinical_200929.csv"
SPIROMICS_RACE_COL = "RACE"
SPIROMICS_GENDER_COL = "GENDER"
SPIROMICS_SID_COL = "SUBJID"
SPIROMICS_AGE_COL = "AGE_DERV_V1"

PAIR_LIST = "output/use_pqtls_p1_only.csv"
REFERENCE_SNPS = "output/reference_snps_p1.csv"